language: rust
sudo: false

cache:
  - cargo

env:
  RUSTINFRA_DEPLOY_DIR: book
import:
  - rust-lang/simpleinfra:travis-configs/static-websites.yml

rust:
  - stable

before_script:
  - cargo install --version "^0.4.5" mdbook
  - cargo install --version "^1.3.1" skill-tree

script:
  - mdbook build && mdbook test
  - skill-tree roadmap.toml book/roadmap
